from .dashboard import dashboard_page
from .index import index_page
from .logout import logout_page
from .onboard import onboard_page
from .report_assign import assign_page
from .report_comp import comp_page
from .report_complete import complete_page
from .report_staffing import staffing_page
from .report_summary import summary_page
from .report_summary_assign import assign_summary_page
from .report_summary_comp import comp_summary_page
from .report_summary_staffing import staffing_summary_page
from .search import search_page