state_abbr_dict = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "Washington (DC)": "DC",
    "West Virgina": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY"
}

cities_by_state = {
    "AK": [
        "Anchorage",
        "Palmer",
        "Juneau",
        "Fairbanks",
        "Bethel",
        "Soldotna",
        "Jber",
        "Fort Wainwright",
        "Valdez",
        "Seward",
        "Petersburg",
        "Wrangell",
        "Kodiak",
        "Cordova",
        "Nome",
        "Dillingham",
        "Kotzebue",
        "Ketchikan",
        "Barrow",
        "Homer",
        "Sitka"
    ],
    "AL": [
        "Dothan",
        "Boaz",
        "Florence",
        "Opp",
        "Luverne",
        "Birmingham",
        "Fort Payne",
        "Alabaster",
        "Sheffield",
        "Ozark",
        "Centre",
        "Montgomery",
        "Opelika",
        "Tallassee",
        "Cullman",
        "Andalusia",
        "Anniston",
        "Huntsville",
        "Gadsden",
        "Hamilton",
        "Fayette",
        "Enterprise",
        "Eutaw",
        "Dadeville",
        "Centreville",
        "Moulton",
        "Scottsboro",
        "Geneva",
        "Alexander City",
        "Eufaula",
        "Ashland",
        "Athens",
        "Foley",
        "Decatur",
        "Winfield",
        "Mobile",
        "Jasper",
        "Grove Hill",
        "Tuscaloosa",
        "Greensboro",
        "Wetumpka",
        "Brewton",
        "Fairhope",
        "Talladega",
        "Camden",
        "Prattville",
        "Union Springs",
        "Demopolis",
        "Bessemer",
        "Selma",
        "Monroeville",
        "Haleyville",
        "Troy",
        "Jackson",
        "Bay Minette",
        "Pell City",
        "York",
        "Evergreen",
        "Greenville",
        "Muscle Shoals",
        "Russellville",
        "Sylacauga",
        "Phenix City",
        "Atmore",
        "Clanton",
        "Thomasville",
        "Valley",
        "Chatom",
        "Red Bay",
        "Butler",
        "Oneonta",
        "Wedowee",
        "Daphne"
    ],
    "AR": [
        "Siloam Springs",
        "Clarksville",
        "Fayetteville",
        "Little Rock",
        "Rogers",
        "Danville",
        "Searcy",
        "Mena",
        "Harrison",
        "Van Buren",
        "Forrest City",
        "Jonesboro",
        "Springdale",
        "Hot Springs",
        "Mountain Home",
        "Conway",
        "North Little Rock",
        "Paragould",
        "Russellville",
        "Pocahontas",
        "Camden",
        "Monticello",
        "Fort Smith",
        "Magnolia",
        "Blytheville",
        "Pine Bluff",
        "Stuttgart",
        "Jacksonville",
        "Malvern",
        "Benton",
        "Helena",
        "El Dorado",
        "Batesville",
        "Sherwood",
        "No Little Rock",
        "Hope",
        "West Memphis",
        "Bryant",
        "Paris",
        "Dardanelle",
        "Ozark",
        "Eureka Springs",
        "Waldron",
        "Calico Rock",
        "Wynne",
        "Mcgehee",
        "Walnut Ridge",
        "Mountain View",
        "Nashville",
        "Heber Springs",
        "Clinton",
        "De Witt",
        "Osceola",
        "Fordyce",
        "Booneville",
        "Ashdown",
        "Arkadelphia",
        "Salem",
        "Crossett",
        "Morrilton",
        "Dumas",
        "Warren",
        "Lake Village",
        "Berryville",
        "Piggott",
        "Gravette",
        "Barling",
        "Maumelle",
        "Texarkana"
    ],
    "AZ": [
        "Phoenix",
        "Tucson",
        "Cottonwood",
        "Prescott",
        "Yuma",
        "Casa Grande",
        "Flagstaff",
        "Chandler",
        "Scottsdale",
        "Sierra Vista",
        "Kingman",
        "Sun City",
        "Show Low",
        "Mesa",
        "Lake Havasu City",
        "Fort Defiance",
        "Tuba City",
        "Sells",
        "Peridot",
        "Chinle",
        "Glendale",
        "Sun City West",
        "Bullhead City",
        "Goodyear",
        "Whiteriver",
        "Oro Valley",
        "Fort Mohave",
        "Gilbert",
        "Queen Creek",
        "Apache Junction",
        "Laveen",
        "Green Valley",
        "Sahuarita",
        "Wickenburg",
        "Benson",
        "Willcox",
        "Page",
        "Polacca",
        "Parker",
        "Sacaton",
        "Ganado",
        "Winslow",
        "Bisbee",
        "Nogales",
        "Globe",
        "Springerville",
        "Payson",
        "Prescott Valley",
        "Lakeside",
        "Tempe",
        "Avondale",
        "Surprise"
    ],
    "CA": [
        "Hayward",
        "Eureka",
        "Burlingame",
        "San Francisco",
        "Napa",
        "Saint Helena",
        "Jackson",
        "Sacramento",
        "Riverside",
        "National City",
        "San Diego",
        "La Mesa",
        "Arcata",
        "Oroville",
        "Bakersfield",
        "San Jose",
        "Chico",
        "Sylmar",
        "Red Bluff",
        "Oakland",
        "El Centro",
        "Banning",
        "Lancaster",
        "Visalia",
        "Glendale",
        "Fresno",
        "Los Angeles",
        "Oakdale",
        "Orange",
        "South San Francisco",
        "Santa Clara",
        "Walnut Creek",
        "Vallejo",
        "San Pedro",
        "Oxnard",
        "Stockton",
        "San Bernardino",
        "Sonoma",
        "Huntington Park",
        "West Covina",
        "Upland",
        "Lynwood",
        "Santa Maria",
        "Lompoc",
        "Santa Monica",
        "San Mateo",
        "Escondido",
        "Northridge",
        "Manteca",
        "Hanford",
        "Van Nuys",
        "Woodland",
        "Oceanside",
        "Novato",
        "San Gabriel",
        "Marysville",
        "Hollywood",
        "Petaluma",
        "Panorama City",
        "Downey",
        "Fontana",
        "Monterey",
        "Grass Valley",
        "Encino",
        "Ventura",
        "Fairfield",
        "French Camp",
        "Fullerton",
        "Whittier",
        "Santa Rosa",
        "Turlock",
        "Long Beach",
        "Reedley",
        "Watsonville",
        "Fremont",
        "Redwood City",
        "Palmdale",
        "Camp Pendleton",
        "Alameda",
        "Chula Vista",
        "Newport Beach",
        "Anaheim",
        "Garden Grove",
        "Pomona",
        "San Luis Obispo",
        "Coronado",
        "Burbank",
        "Simi Valley",
        "Arcadia",
        "Santa Cruz",
        "Palm Springs",
        "Colton",
        "Salinas",
        "Placerville",
        "Porterville",
        "Redlands",
        "Martinez",
        "Mission Hills",
        "Joshua Tree",
        "Redding",
        "Alhambra",
        "Pleasanton",
        "Daly City",
        "Moreno Valley",
        "Barstow",
        "Apple Valley",
        "Ukiah",
        "Berkeley",
        "Mountain View",
        "Roseville",
        "Tracy",
        "La Jolla",
        "Loma Linda",
        "Corona",
        "Sonora",
        "Lodi",
        "Brawley",
        "Montebello",
        "Torrance",
        "South Lake Tahoe",
        "Santa Barbara",
        "Greenbrae",
        "Sun Valley",
        "Covina",
        "Hemet",
        "Twentynine Palms",
        "Harbor City",
        "Folsom",
        "Crescent City",
        "Fort Irwin",
        "Blythe",
        "Pasadena",
        "Stanford",
        "Merced",
        "Modesto",
        "Gardena",
        "West Hills",
        "Castro Valley",
        "Clovis",
        "Concord",
        "Auburn",
        "Encinitas",
        "San Rafael",
        "Carmichael",
        "Victorville",
        "Antioch",
        "Huntington Beach",
        "Los Banos",
        "Indio",
        "Davis",
        "Costa Mesa",
        "Thousand Oaks",
        "Los Alamitos",
        "Mission Viejo",
        "Madera",
        "Fountain Valley",
        "Rancho Mirage",
        "La Palma",
        "Lakewood",
        "Chino",
        "San Dimas",
        "Placentia",
        "Glendora",
        "Laguna Hills",
        "Delano",
        "Valencia",
        "Templeton",
        "Poway",
        "Woodland Hills",
        "Sun City",
        "San Ramon",
        "Murrieta",
        "Baldwin Park",
        "Monterey Park",
        "South El Monte",
        "Inglewood",
        "Marina Del Rey",
        "Santa Ana",
        "Sherman Oaks",
        "Montclair",
        "Tarzana",
        "Yuba City",
        "Vacaville",
        "Irvine",
        "Norwalk",
        "Temecula",
        "San Leandro",
        "Tustin",
        "Colusa",
        "Tulare",
        "Portola",
        "Tehachapi",
        "Lone Pine",
        "Mammoth Lakes",
        "Mariposa",
        "Fall River Mills",
        "Willows",
        "Avalon",
        "Cedarville",
        "Garberville",
        "Willits",
        "Gridley",
        "Lake Arrowhead",
        "Lake Isabella",
        "Weaverville",
        "Yreka",
        "Clearlake",
        "Fortuna",
        "Mount Shasta",
        "Susanville",
        "Healdsburg",
        "Needles",
        "Bishop",
        "Fort Bragg",
        "Quincy",
        "Chester",
        "Truckee",
        "Lakeport",
        "Alturas",
        "Solvang",
        "San Andreas",
        "Ridgecrest",
        "Ojai",
        "Big Bear Lake",
        "King City",
        "Hollister",
        "Palo Alto",
        "Rosemead",
        "Cerritos",
        "Reseda"
        ],
    "CO": [
        "Greeley",
        "Longmont",
        "Brighton",
        "Montrose",
        "Alamosa",
        "Wheat Ridge",
        "Fort Collins",
        "Denver",
        "Pueblo",
        "Durango",
        "Lakewood",
        "Colorado Springs",
        "Grand Junction",
        "Aurora",
        "Boulder",
        "Loveland",
        "Englewood",
        "Fort Carson",
        "Fort Morgan",
        "Steamboat Springs",
        "Thornton",
        "Delta",
        "Glenwood Springs",
        "Sterling",
        "Vail",
        "Louisville",
        "Westminster",
        "Lone Tree",
        "Littleton",
        "Parker",
        "Lafayette",
        "Frisco",
        "Castle Rock",
        "Broomfield",
        "Highlands Ranch",
        "Eads",
        "Del Norte",
        "Fruita",
        "Brush",
        "Haxtun",
        "Holyoke",
        "Hugo",
        "Rangely",
        "La Jara",
        "Wray",
        "Julesburg",
        "Springfield",
        "Estes Park",
        "Burlington",
        "Craig",
        "Yuma",
        "Walsenburg",
        "Rifle",
        "Kremmling",
        "Leadville",
        "Gunnison",
        "Trinidad",
        "Salida",
        "Lamar",
        "Aspen",
        "Meeker",
        "Woodland Park",
        "Cortez",
        "Pagosa Springs",
        "La Junta",
        "Cheyenne Wells",
        "Canon City"
    ],
    "CT": [
        "Hartford",
        "Putnam",
        "Sharon",
        "Waterbury",
        "Stamford",
        "New London",
        "Stafford Springs",
        "Bridgeport",
        "Torrington",
        "Rockville",
        "Meriden",
        "Greenwich",
        "Middletown",
        "Willimantic",
        "New Haven",
        "Norwich",
        "Manchester",
        "Bristol",
        "Derby",
        "Danbury",
        "Norwalk",
        "New Britain",
        "Farmington",
        "Branford",
        "Wallingford",
        "West Hartford",
        "Mansfield Center",
        "New Canaan"
    ],
    "DC": [
        "Washington"
    ],
    "DE": [
        "Newark",
        "Wilmington",
        "Dover",
        "Seaford",
        "Lewes",
        "Milford",
        "New Castle",
        "Georgetown"
    ],
    "FL": [
        "Jacksonville",
        "Boynton Beach",
        "Orlando",
        "Miami",
        "Fort Myers",
        "New Smyrna Beach",
        "Daytona Beach",
        "Naples",
        "Melbourne",
        "Inverness",
        "Pensacola",
        "Panama City",
        "Titusville",
        "Ocoee",
        "Saint Petersburg",
        "Miami Beach",
        "Bradenton",
        "Hollywood",
        "Fort Lauderdale",
        "Dunedin",
        "Stuart",
        "Deland",
        "Zephyrhills",
        "Punta Gorda",
        "Jay",
        "Sebring",
        "Hialeah",
        "Clermont",
        "Winter Haven",
        "Niceville",
        "Tarpon Springs",
        "Tavares",
        "Ocala",
        "New Port Richey",
        "Tampa",
        "Venice",
        "Brooksville",
        "Orange City",
        "Port Charlotte",
        "Atlantis",
        "Defuniak Springs",
        "Leesburg",
        "Pompano Beach",
        "Sarasota",
        "Saint Augustine",
        "Rockledge",
        "Lake Wales",
        "Vero Beach",
        "Perry",
        "Lehigh Acres",
        "Kissimmee",
        "Gainesville",
        "Jacksonville Beach",
        "Palm Coast",
        "Bartow",
        "Crestview",
        "Milton",
        "Homestead",
        "Clearwater",
        "Belle Glade",
        "Aventura",
        "Plant City",
        "Macclenny",
        "Tallahassee",
        "Davenport",
        "Fernandina Beach",
        "Marianna",
        "Key West",
        "South Miami",
        "Lake City",
        "Lakeland",
        "Sanford",
        "Plantation",
        "Boca Raton",
        "Arcadia",
        "Palm Beach Gardens",
        "Cocoa Beach",
        "Coral Gables",
        "Margate",
        "Trinity",
        "Dade City",
        "Sebastian",
        "Eglin Afb",
        "Fort Walton Beach",
        "Tamarac",
        "Orange Park",
        "Pembroke Pines",
        "Palatka",
        "Brandon",
        "Cape Coral",
        "Fort Pierce",
        "Largo",
        "Crystal River",
        "Okeechobee",
        "Jupiter",
        "Hudson",
        "Delray Beach",
        "Sun City Center",
        "Port Saint Lucie",
        "Safety Harbor",
        "Gulf Breeze",
        "Englewood",
        "Loxahatchee",
        "Wellington",
        "Coral Springs",
        "Miramar",
        "West Palm Beach",
        "Weston",
        "The Villages",
        "Miramar Beach",
        "Chattahoochee",
        "Saint Cloud",
        "Port Saint Joe",
        "Palm Bay",
        "Wesley Chapel",
        "Middleburg",
        "Oviedo",
        "Deltona",
        "Wauchula",
        "Lake Butler",
        "Blountstown",
        "Apalachicola",
        "Bonifay",
        "Chipley",
        "Clewiston",
        "Madison",
        "Marathon",
        "Tavernier",
        "Oakland Park"
    ],
    "GA": [
        "Dalton",
        "Thomaston",
        "Waycross",
        "Cumming",
        "Athens",
        "Albany",
        "Canton",
        "Atlanta",
        "Carrollton",
        "Villa Rica",
        "Lagrange",
        "Covington",
        "Calhoun",
        "Savannah",
        "Brunswick",
        "Lavonia",
        "Augusta",
        "Gainesville",
        "Cartersville",
        "Griffin",
        "Toccoa",
        "Marietta",
        "Thomasville",
        "Demorest",
        "Hiram",
        "Americus",
        "Winder",
        "Monroe",
        "Chatsworth",
        "Blairsville",
        "Rome",
        "Columbus",
        "Warner Robins",
        "Baxley",
        "Fitzgerald",
        "Statesboro",
        "Decatur",
        "Sandersville",
        "Lawrenceville",
        "Douglas",
        "Conyers",
        "Eastman",
        "Tifton",
        "Louisville",
        "Adel",
        "Cordele",
        "Moultrie",
        "Macon",
        "Swainsboro",
        "Thomson",
        "Waynesboro",
        "Cairo",
        "Valdosta",
        "Jesup",
        "Dublin",
        "Vidalia",
        "Ocilla",
        "Bainbridge",
        "Hawkinsville",
        "Claxton",
        "Austell",
        "Saint Marys",
        "Milledgeville",
        "Perry",
        "Riverdale",
        "Douglasville",
        "Blue Ridge",
        "Montezuma",
        "Stockbridge",
        "Snellville",
        "Donalsonville",
        "Roswell",
        "Fayetteville",
        "Jasper",
        "Lithonia",
        "Newnan",
        "Johns Creek",
        "Nashville",
        "Fort Oglethorpe",
        "Dahlonega",
        "Duluth",
        "Fort Benning",
        "Fort Gordon",
        "Fort Stewart",
        "Cochran",
        "Monticello",
        "Madison",
        "Colquitt",
        "Springfield",
        "Homerville",
        "Byron",
        "Millen",
        "Sylvania",
        "Eatonton",
        "Blakely",
        "Warm Springs",
        "Forsyth",
        "Jackson",
        "Bremen",
        "Reidsville",
        "Hiawassee",
        "Washington",
        "Lakeland",
        "Alma",
        "Sylvester",
        "Greensboro",
        "Cedartown",
        "Camilla",
        "Quitman",
        "Hazlehurst",
        "Metter",
        "Hinesville",
        "Clayton",
        "Elberton",
        "Smyrna",
        "Saint Simons Island",
        "College Park"
    ],
    "HI": [
        "Honolulu",
        "Wailuku",
        "Wahiawa",
        "Hilo",
        "Kailua",
        "Lihue",
        "Kealakekua",
        "Aiea",
        "Kamuela",
        "Waimea",
        "Pahala",
        "Kapaau",
        "Kaunakakai",
        "Kahuku",
        "Lanai City",
        "Kapaa",
        "Honokaa",
        "Kula",
        "Ewa Beach"
    ],
    "ID": [
        "Twin Falls",
        "Lewiston",
        "Boise",
        "Nampa",
        "Caldwell",
        "Idaho Falls",
        "Rexburg",
        "Pocatello",
        "Coeur D'Alene",
        "Post Falls",
        "Blackfoot",
        "Bonners Ferry",
        "Gooding",
        "Malad",
        "American Falls",
        "Salmon",
        "Weiser",
        "Cascade",
        "Soda Springs",
        "Jerome",
        "Mountain Home",
        "Mccall",
        "Driggs",
        "Kellogg",
        "Grangeville",
        "Montpelier",
        "St Maries",
        "Emmett",
        "Rupert",
        "Orofino",
        "Cottonwood",
        "Preston",
        "Ketchum",
        "Arco",
        "Burley",
        "Moscow",
        "Sandpoint",
        "Meridian"
    ],
    "IL": [
        "Canton",
        "Alton",
        "Joliet",
        "Melrose Park",
        "Evanston",
        "Herrin",
        "Dixon",
        "Peoria",
        "Quincy",
        "Chicago",
        "Shelbyville",
        "Aurora",
        "Elgin",
        "Effingham",
        "Centralia",
        "Galesburg",
        "Sterling",
        "Mount Vernon",
        "Oak Park",
        "Springfield",
        "Berwyn",
        "Jacksonville",
        "Jerseyville",
        "Palos Heights",
        "La Grange",
        "Centreville",
        "Waukegan",
        "Macomb",
        "Urbana",
        "Danville",
        "Zion",
        "Morris",
        "Ottawa",
        "Mchenry",
        "Pekin",
        "Hinsdale",
        "Granite City",
        "Normal",
        "Lake Forest",
        "Decatur",
        "Greenville",
        "Spring Valley",
        "Breese",
        "Olney",
        "Kankakee",
        "Freeport",
        "Pontiac",
        "Bloomington",
        "Carbondale",
        "Watseka",
        "Olympia Fields",
        "Evergreen Park",
        "Marion",
        "Belleville",
        "O Fallon",
        "Mattoon",
        "Harvey",
        "Elmhurst",
        "Libertyville",
        "Oak Lawn",
        "Harrisburg",
        "Geneva",
        "New Lenox",
        "Park Ridge",
        "Rockford",
        "Naperville",
        "Peru",
        "Winfield",
        "Arlington Heights",
        "Elk Grove Village",
        "Silvis",
        "Maywood",
        "Rock Island",
        "Dekalb",
        "Downers Grove",
        "Maryville",
        "Hoffman Estates",
        "Barrington",
        "Glendale Heights",
        "Bolingbrook",
        "Carrollton",
        "Monticello",
        "Galena",
        "Clinton",
        "Aledo",
        "Carthage",
        "Staunton",
        "Pinckneyville",
        "Nashville",
        "Eureka",
        "Mendota",
        "Fairfield",
        "Rochelle",
        "Havana",
        "Pittsfield",
        "Hoopeston",
        "Gibson City",
        "Monmouth",
        "Geneseo",
        "Paris",
        "Benton",
        "Lincoln",
        "Metropolis",
        "Eldorado",
        "Kewanee",
        "Mcleansboro",
        "Mount Carmel",
        "Rosiclare",
        "Morrison",
        "Hopedale",
        "Du Quoin",
        "Hillsboro",
        "Rushville",
        "Murphysboro",
        "Harvard",
        "Highland",
        "Princeton",
        "Chester",
        "Taylorville",
        "Sandwich",
        "Pana",
        "Anna",
        "Robinson",
        "Lawrenceville",
        "Salem",
        "Vandalia",
        "Carlinville",
        "Red Bud",
        "Sparta",
        "Litchfield",
        "Flora",
        "Forest Park",
        "Hines",
        "Champaign",
        "Streamwood",
        "Des Plaines"
    ],
    "IN": [
        "Franklin",
        "Gary",
        "Hammond",
        "Danville",
        "La Porte",
        "Kokomo",
        "East Chicago",
        "Jeffersonville",
        "Marion",
        "Mishawaka",
        "Michigan City",
        "Fort Wayne",
        "Elkhart",
        "Crawfordsville",
        "Terre Haute",
        "Indianapolis",
        "Goshen",
        "New Castle",
        "Hobart",
        "Valparaiso",
        "Greenfield",
        "Vincennes",
        "New Albany",
        "Auburn",
        "Richmond",
        "Bloomington",
        "Mooresville",
        "South Bend",
        "Noblesville",
        "Washington",
        "Seymour",
        "Madison",
        "Logansport",
        "Bluffton",
        "Plymouth",
        "Evansville",
        "Lawrenceburg",
        "Anderson",
        "Muncie",
        "Dyer",
        "Huntington",
        "Shelbyville",
        "Columbia City",
        "Knox",
        "Lebanon",
        "Lafayette",
        "Columbus",
        "Jasper",
        "Munster",
        "Crown Point",
        "Warsaw",
        "Kendallville",
        "Newburgh",
        "Carmel",
        "Avon",
        "Fishers",
        "Bremen",
        "Winchester",
        "Hartford City",
        "North Vernon",
        "Rushville",
        "Winamac",
        "Paoli",
        "Williamsport",
        "Elwood",
        "Brazil",
        "Wabash",
        "Tipton",
        "Monticello",
        "Rochester",
        "Salem",
        "Angola",
        "Frankfort",
        "Linton",
        "Peru",
        "Princeton",
        "Portland",
        "Tell City",
        "Lagrange",
        "Rensselaer",
        "Boonville",
        "Clinton",
        "Sullivan",
        "Bedford",
        "Batesville",
        "Decatur",
        "Corydon",
        "Greensburg",
        "Greencastle",
        "Scottsburg",
        "West Lafayette",
        "Pierceton",
        "Merrillville",
        "Greenwood"
    ],
    "IA": [
        "Marshalltown",
        "Carroll",
        "Keokuk",
        "Muscatine",
        "Fort Dodge",
        "Council Bluffs",
        "Iowa City",
        "Ames",
        "Newton",
        "Davenport",
        "Cedar Falls",
        "Cedar Rapids",
        "West Burlington",
        "Mason City",
        "Waterloo",
        "Dubuque",
        "Clinton",
        "Des Moines",
        "Ottumwa",
        "Bettendorf",
        "Spencer",
        "Spirit Lake",
        "Sioux City",
        "Grinnell",
        "Primghar",
        "Belmond",
        "Clarion",
        "Grundy Center",
        "Corning",
        "Pocahontas",
        "Anamosa",
        "Britt",
        "Hampton",
        "Missouri Valley",
        "Greenfield",
        "Hawarden",
        "Guttenberg",
        "Dewitt",
        "Guthrie Center",
        "Sigourney",
        "West Union",
        "Marengo",
        "Waukon",
        "Elkader",
        "Sumner",
        "Rock Rapids",
        "Perry",
        "Osage",
        "Hamburg",
        "Jefferson",
        "Winterset",
        "Bloomfield",
        "Cresco",
        "Maquoketa",
        "Audubon",
        "New Hampton",
        "Manning",
        "Nevada",
        "Humboldt",
        "Independence",
        "Rock Valley",
        "Keosauqua",
        "Oelwein",
        "Waverly",
        "Leon",
        "Chariton",
        "Albia",
        "Manchester",
        "Washington",
        "Sibley",
        "Sioux Center",
        "Charles City",
        "Osceola",
        "Vinton",
        "Lake City",
        "Estherville",
        "Clarinda",
        "Algona",
        "Ida Grove",
        "Knoxville",
        "Mount Pleasant",
        "Emmetsburg",
        "Corydon",
        "Onawa",
        "Orange City",
        "Webster City",
        "Cherokee",
        "Red Oak",
        "Fairfield",
        "Creston",
        "Shenandoah",
        "Pella",
        "Le Mars",
        "Denison",
        "Sac City",
        "Decorah",
        "Boone",
        "Mount Ayr",
        "Harlan",
        "Storm Lake",
        "Atlantic",
        "Centerville",
        "Dyersville",
        "Oskaloosa",
        "Iowa Falls",
        "Sheldon",
        "Clive"
    ],
    "KS": [
        "Pittsburg",
        "Leavenworth",
        "Salina",
        "Hays",
        "Ottawa",
        "Topeka",
        "El Dorado",
        "Hutchinson",
        "Garden City",
        "Pratt",
        "Fort Riley",
        "Kansas City",
        "Olathe",
        "Liberal",
        "Junction City",
        "Moundridge",
        "Newton",
        "Shawnee Mission",
        "Mcpherson",
        "Paola",
        "Ulysses",
        "Parsons",
        "Wichita",
        "Lawrence",
        "Manhattan",
        "Coffeyville",
        "Arkansas City",
        "Elkhart",
        "Dodge City",
        "Overland Park",
        "Leawood",
        "Great Bend",
        "Andover",
        "Lenexa",
        "Galena",
        "Derby",
        "Ransom",
        "Ellinwood",
        "Dighton",
        "Ashland",
        "Leoti",
        "Atwood",
        "Columbus",
        "Mankato",
        "St Francis",
        "Plainville",
        "Coldwater",
        "Lakin",
        "Winchester",
        "Seneca",
        "Garnett",
        "Kinsley",
        "Sedan",
        "Holton",
        "Meade",
        "Syracuse",
        "Stafford",
        "Satanta",
        "Hill City",
        "Oakley",
        "Ellsworth",
        "Minneapolis",
        "Caldwell",
        "Lyons",
        "Kiowa",
        "Greensburg",
        "Hoisington",
        "Medicine Lodge",
        "Hugoton",
        "Ness City",
        "Wamego",
        "Sabetha",
        "Eureka",
        "Herington",
        "Hiawatha",
        "La Crosse",
        "Johnson",
        "Neodesha",
        "Larned",
        "Anthony",
        "Hoxie",
        "Norton",
        "Concordia",
        "Russell",
        "Washington",
        "Oberlin",
        "Phillipsburg",
        "Onaga",
        "Wa Keeney",
        "Marion",
        "Hillsboro",
        "Lindsborg",
        "Tribune",
        "Lincoln",
        "Belleville",
        "Colby",
        "Marysville",
        "Osborne",
        "Hanover",
        "Quinter",
        "Minneola",
        "Jetmore",
        "Goodland",
        "Clay Center",
        "Scott City",
        "Iola",
        "Fredonia",
        "Beloit",
        "Girard",
        "Smith Center",
        "Kingman",
        "Council Grove",
        "Chanute",
        "Abilene",
        "Atchison",
        "Winfield",
        "Emporia",
        "Burlington",
        "Osawatomie"
    ],
    "KY": [
        "Fort Thomas",
        "Whitesburg",
        "Greenville",
        "Prestonsburg",
        "Ashland",
        "Lexington",
        "London",
        "Elizabethtown",
        "Bowling Green",
        "Shelbyville",
        "Glasgow",
        "Morehead",
        "Maysville",
        "Middlesboro",
        "Lebanon",
        "Bardstown",
        "Murray",
        "Hazard",
        "Edgewood",
        "Owensboro",
        "Fort Campbell",
        "Louisville",
        "Manchester",
        "Pikeville",
        "Florence",
        "Paris",
        "Danville",
        "Richmond",
        "Harlan",
        "Hopkinsville",
        "Henderson",
        "Mount Sterling",
        "Russellville",
        "South Williamson",
        "Leitchfield",
        "Paintsville",
        "Cynthiana",
        "Corbin",
        "Campbellsville",
        "Winchester",
        "Madisonville",
        "Marion",
        "Georgetown",
        "Paducah",
        "Tompkinsville",
        "Albany",
        "Mount Vernon",
        "Mayfield",
        "Frankfort",
        "Louisa",
        "Somerset",
        "La Grange",
        "Jackson",
        "Columbia",
        "Pineville",
        "Irvine",
        "Harrodsburg",
        "Cadiz",
        "Martin",
        "Morganfield",
        "West Liberty",
        "Versailles",
        "Liberty",
        "Carrollton",
        "Williamstown",
        "Horse Cave",
        "Stanford",
        "Hyden",
        "Burkesville",
        "Franklin",
        "Hardinsburg",
        "Salem",
        "Monticello",
        "Princeton",
        "Hartford",
        "Scottsville",
        "Greensburg",
        "Benton",
        "Barbourville",
        "Berea",
        "Russell Springs",
        "Mc Dowell",
        "Flemingsburg",
        "Erlanger",
        "Radcliff"
    ],
    "LA": [
        "Lafayette",
        "Thibodaux",
        "New Orleans",
        "Natchitoches",
        "Houma",
        "Monroe",
        "Sulphur",
        "Morgan City",
        "Hammond",
        "Opelousas",
        "Alexandria",
        "Zachary",
        "Mamou",
        "Lake Charles",
        "Abbeville",
        "Marrero",
        "Slidell",
        "Shreveport",
        "Crowley",
        "Covington",
        "Deridder",
        "Jennings",
        "New Iberia",
        "Baton Rouge",
        "Luling",
        "Oak Grove",
        "Ruston",
        "Springhill",
        "Winnfield",
        "Marksville",
        "Oakdale",
        "Homer",
        "Bastrop",
        "Mansfield",
        "Kinder",
        "Winnsboro",
        "Minden",
        "Jena",
        "Metairie",
        "Rayville",
        "West Monroe",
        "Leesville",
        "Ville Platte",
        "Columbia",
        "Lake Providence",
        "Many",
        "Kenner",
        "Cameron",
        "Chalmette",
        "Bogalusa",
        "Kentwood",
        "Eunice",
        "Fort Polk",
        "Greensburg",
        "Farmerville",
        "Breaux Bridge",
        "Napoleonville",
        "Vivian",
        "Lutcher",
        "Saint Francisville",
        "Dequincy",
        "Donaldsonville",
        "Amite",
        "Franklin",
        "Bunkie",
        "Coushatta",
        "Franklinton",
        "Tallulah",
        "Olla",
        "New Roads",
        "Jonesboro",
        "Ferriday",
        "Church Point",
        "Arcadia",
        "Independence",
        "Kaplan",
        "Delhi",
        "Raceland",
        "Cut Off",
        "Bernice",
        "Mandeville",
        "Jackson",
        "Pineville",
        "Harahan",
        "Broussard",
        "Bossier City",
        "Lacombe",
        "Gonzales",
        "Gretna",
        "La Place"
    ],
    "ME": [
        "Bangor",
        "Portland",
        "Presque Isle",
        "Biddeford",
        "York",
        "Brunswick",
        "Lewiston",
        "Caribou",
        "Farmington",
        "Augusta",
        "Waterville",
        "Ellsworth",
        "Fort Kent",
        "Rockport",
        "Blue Hill",
        "Greenville",
        "Damariscotta",
        "Lincoln",
        "Bar Harbor",
        "Calais",
        "Rumford",
        "Millinocket",
        "Houlton",
        "Dover Foxcroft",
        "Bridgton",
        "Machias",
        "Belfast",
        "Pittsfield",
        "Skowhegan",
        "Norway",
        "Westbrook"
    ],
    "MD": [
        "Hagerstown",
        "Baltimore",
        "Largo",
        "Silver Spring",
        "Frederick",
        "Havre De Grace",
        "Rosedale",
        "Oakland",
        "Olney",
        "Salisbury",
        "Bethesda",
        "Annapolis",
        "Cumberland",
        "Leonardtown",
        "Chestertown",
        "Elkton",
        "Westminster",
        "La Plata",
        "Easton",
        "Prince Frederick",
        "Randallstown",
        "Glen Burnie",
        "Columbia",
        "Bel Air",
        "Lanham",
        "Rockville",
        "Fort Washington",
        "Berlin",
        "Clinton",
        "Towson",
        "Germantown",
        "Cambridge",
        "Sykesville",
        "Catonsville"
    ],
    "MA": [
        "Leominster",
        "Cambridge",
        "Attleboro",
        "Lawrence",
        "Hyannis",
        "Northampton",
        "Greenfield",
        "Boston",
        "Southbridge",
        "Fall River",
        "Holyoke",
        "Newburyport",
        "Palmer",
        "Beverly",
        "Salem",
        "Brighton",
        "Pittsfield",
        "Marlborough",
        "Brockton",
        "Plymouth",
        "Worcester",
        "Lowell",
        "Westfield",
        "Springfield",
        "Melrose",
        "Taunton",
        "Methuen",
        "Needham",
        "W Concord",
        "Milford",
        "Gardner",
        "Ayer",
        "South Weymouth",
        "Newton",
        "Winchester",
        "Milton",
        "Norwood",
        "Falmouth",
        "Burlington",
        "Framingham",
        "Nantucket",
        "Oak Bluffs",
        "Great Barrington",
        "Athol",
        "Belmont",
        "Brookline",
        "South Attleboro",
        "Boston College",
        "Westwood",
        "Pocasset",
        "Dedham",
        "Haverhill",
        "Dartmouth",
        "Devens",
        "Westborough"
    ],
    "MI": [
        "Livonia",
        "Zeeland",
        "Adrian",
        "Pontiac",
        "Three Rivers",
        "Kalamazoo",
        "Southfield",
        "Dearborn",
        "St Joseph",
        "Coldwater",
        "Detroit",
        "Alma",
        "Port Huron",
        "Greenville",
        "Alpena",
        "Hillsdale",
        "Grand Rapids",
        "Bay City",
        "Ann Arbor",
        "Clinton Township",
        "Marquette",
        "Iron Mountain",
        "Grayling",
        "Muskegon",
        "Howell",
        "Saginaw",
        "Holland",
        "Battle Creek",
        "Watervliet",
        "Mount Pleasant",
        "Cadillac",
        "South Haven",
        "Grosse Pointe",
        "Jackson",
        "Big Rapids",
        "West Branch",
        "Sturgis",
        "Traverse City",
        "Monroe",
        "Tawas City",
        "Petoskey",
        "Hancock",
        "Ludington",
        "Owosso",
        "Royal Oak",
        "Flint",
        "Gaylord",
        "Wayne",
        "Ypsilanti",
        "Wyandotte",
        "Farmington Hills",
        "Lansing",
        "Grand Haven",
        "Trenton",
        "Clare",
        "Lapeer",
        "Warren",
        "Grand Blanc",
        "Carson City",
        "Marshall",
        "Midland",
        "Mount Clemens",
        "Wyoming",
        "Sault Sainte Marie",
        "East China",
        "Garden City",
        "Rochester",
        "Chelsea",
        "Troy",
        "Taylor",
        "Commerce Township",
        "Brighton",
        "West Bloomfield",
        "Manistee",
        "Frankfort",
        "Kalkaska",
        "Manistique",
        "Newberry",
        "Standish",
        "Saint Ignace",
        "L' Anse",
        "Munising",
        "Ontonagon",
        "Pigeon",
        "Deckerville",
        "Sheridan",
        "Harbor Beach",
        "Sandusky",
        "Dowagiac",
        "Cass City",
        "Lakeview",
        "Iron River",
        "Laurium",
        "Shelby",
        "Ishpeming",
        "Charlevoix",
        "Reed City",
        "Eaton Rapids",
        "Gladwin",
        "Saint Johns",
        "Charlotte",
        "Allegan",
        "Caro",
        "Marlette",
        "Ionia",
        "Paw Paw",
        "Ironwood",
        "Escanaba",
        "Fremont",
        "Hastings",
        "Bad Axe",
        "Ferndale",
        "New Baltimore",
        "Auburn Hills",
        "Westland",
        "Saline"
    ],
    "MN": [
        "Robbinsdale",
        "Duluth",
        "Minneapolis",
        "Rochester",
        "Northfield",
        "Red Wing",
        "Cambridge",
        "Worthington",
        "Alexandria",
        "Saint Cloud",
        "Saint Paul",
        "Hibbing",
        "Albert Lea",
        "Winona",
        "Wyoming",
        "Fergus Falls",
        "Saint Louis Park",
        "Waconia",
        "Hastings",
        "Grand Rapids",
        "Stillwater",
        "Owatonna",
        "Faribault",
        "Brainerd",
        "Buffalo",
        "Edina",
        "Virginia",
        "Willmar",
        "Mankato",
        "Bemidji",
        "Detroit Lakes",
        "Shakopee",
        "Coon Rapids",
        "Princeton",
        "Fairmont",
        "Hutchinson",
        "Redlake",
        "Burnsville",
        "Maplewood",
        "Woodbury",
        "Maple Grove",
        "Mahnomen",
        "Baudette",
        "Westbrook",
        "Tracy",
        "Wheaton",
        "Aitkin",
        "Olivia",
        "Two Harbors",
        "Sandstone",
        "Arlington",
        "Cook",
        "Ada",
        "Dawson",
        "Jackson",
        "Bigfork",
        "Grand Marais",
        "Ely",
        "Slayton",
        "Crookston",
        "Graceville",
        "International Falls",
        "Madelia",
        "Montevideo",
        "Long Prairie",
        "Sleepy Eye",
        "Bagley",
        "Staples",
        "Melrose",
        "Windom",
        "St James",
        "St Peter",
        "Wabasha",
        "Hallock",
        "Warren",
        "Lake City",
        "Hendricks",
        "Aurora",
        "Appleton",
        "Ortonville",
        "Granite Falls",
        "Roseau",
        "Waseca",
        "Cannon Falls",
        "Canby",
        "Tyler",
        "Paynesville",
        "Moose Lake",
        "Redwood Falls",
        "Crosby",
        "Wadena",
        "Glencoe",
        "Onamia",
        "Fosston",
        "Cass Lake",
        "Marshall",
        "Deer River",
        "New Prague",
        "Monticello",
        "Morris",
        "Cloquet",
        "Benson",
        "Litchfield",
        "Mora",
        "Sauk Centre",
        "Blue Earth",
        "Little Falls",
        "Luverne",
        "Madison",
        "Perham",
        "Pipestone",
        "Le Sueur",
        "Glenwood",
        "Breckenridge",
        "New Ulm",
        "Elbow Lake",
        "Park Rapids",
        "Thief River Falls",
        "Anoka",
        "Annandale",
        "Baxter"
    ],
    "MS": [
        "Jackson",
        "Iuka",
        "Tupelo",
        "New Albany",
        "Biloxi",
        "Corinth",
        "Holly Springs",
        "Houston",
        "Bay Springs",
        "Gulfport",
        "Eupora",
        "Amory",
        "Louisville",
        "Vicksburg",
        "Oxford",
        "Lucedale",
        "Canton",
        "Pascagoula",
        "Clarksdale",
        "Philadelphia",
        "Booneville",
        "Magnolia",
        "Starkville",
        "Brookhaven",
        "Laurel",
        "Fayette",
        "Water Valley",
        "West Point",
        "Meridian",
        "Waynesboro",
        "Hattiesburg",
        "Greenville",
        "Natchez",
        "Columbia",
        "Cleveland",
        "Indianola",
        "Brandon",
        "Mccomb",
        "Greenwood",
        "Columbus",
        "Picayune",
        "Magee",
        "Batesville",
        "Whitfield",
        "Flowood",
        "Southaven",
        "Bay Saint Louis",
        "Raleigh",
        "Olive Branch",
        "Grenada",
        "Forest",
        "Aberdeen",
        "Charleston",
        "Monticello",
        "Richton",
        "Macon",
        "Pontotoc",
        "Centreville",
        "Winona",
        "Yazoo City",
        "Marks",
        "Carthage",
        "Quitman",
        "Mendenhall",
        "Ruleville",
        "Lexington",
        "Port Gibson",
        "Union",
        "Morton",
        "Tylertown",
        "Collins",
        "Prentiss",
        "Hazlehurst",
        "Leakesville",
        "Meadville",
        "Calhoun City",
        "Poplarville",
        "Ackerman",
        "De Kalb",
        "Kosciusko",
        "Ripley",
        "Rolling Fork",
        "Purvis"
    ],
    "MO": [
        "Joplin",
        "Saint Charles",
        "Saint Joseph",
        "Sedalia",
        "Jefferson City",
        "Rolla",
        "Saint Louis",
        "Kirksville",
        "Festus",
        "Houston",
        "Hannibal",
        "Kansas City",
        "Fort Leonard Wood",
        "Butler",
        "Springfield",
        "Maryville",
        "Washington",
        "Cameron",
        "Lebanon",
        "Nevada",
        "Mexico",
        "Columbia",
        "Hayti",
        "Moberly",
        "West Plains",
        "Fenton",
        "Richmond Heights",
        "Branson",
        "Independence",
        "North Kansas City",
        "Warrensburg",
        "Bridgeton",
        "Town And Country",
        "Cape Girardeau",
        "Sikeston",
        "Poplar Bluff",
        "Marshall",
        "Dexter",
        "Creve Coeur",
        "Farmington",
        "Clinton",
        "Liberty",
        "Chesterfield",
        "Osage Beach",
        "Lees Summit",
        "Saint Peters",
        "Blue Springs",
        "Bolivar",
        "Lake Saint Louis",
        "Fulton",
        "Belton",
        "O Fallon",
        "Appleton City",
        "Fredericktown",
        "Fairfax",
        "Unionville",
        "Milan",
        "Brookfield",
        "Potosi",
        "Trenton",
        "Memphis",
        "Perryville",
        "Bethany",
        "Macon",
        "Hermann",
        "Bonne Terre",
        "Aurora",
        "Cassville",
        "Salem",
        "Troy",
        "Lexington",
        "Chillicothe",
        "Excelsior Springs",
        "El Dorado Springs",
        "Harrisonville",
        "Lamar",
        "Richmond",
        "Albany",
        "Monett",
        "Sainte Genevieve",
        "Neosho",
        "Carrollton",
        "Louisiana",
        "Mountain View",
        "Pilot Knob",
        "Sullivan",
        "Carthage",
        "Maryland Heights",
        "Windsor"
    ],
    "MT": [
        "Helena",
        "Billings",
        "Great Falls",
        "Missoula",
        "Butte",
        "Havre",
        "Kalispell",
        "Bozeman",
        "Browning",
        "Poplar",
        "Baker",
        "Ekalaka",
        "Philipsburg",
        "Fort Benton",
        "Circle",
        "White Sulphur Spring",
        "Choteau",
        "Culbertson",
        "Terry",
        "Jordan",
        "Big Sandy",
        "Malta",
        "Big Timber",
        "Deer Lodge",
        "Harlem",
        "Glasgow",
        "Livingston",
        "Dillon",
        "Sheridan",
        "Libby",
        "Harlowton",
        "Plentywood",
        "Plains",
        "Conrad",
        "Ronan",
        "Red Lodge",
        "Forsyth",
        "Shelby",
        "Ennis",
        "Columbus",
        "Superior",
        "Glendive",
        "Townsend",
        "Chester",
        "Anaconda",
        "Whitefish",
        "Cut Bank",
        "Hardin",
        "Crow Agency",
        "Hamilton",
        "Wolf Point",
        "Scobey",
        "Polson",
        "Sidney",
        "Lewistown",
        "Roundup",
        "Miles City",
        "Big Sky",
        "Warm Springs"
    ],
    "NC": [
        "Siler City",
        "Greenville",
        "Pinehurst",
        "Rocky Mount",
        "Mount Airy",
        "Danbury",
        "Bryson City",
        "Asheboro",
        "Lenoir",
        "Brevard",
        "Clyde",
        "Cherokee",
        "Salisbury",
        "Elizabeth City",
        "Murphy",
        "Leland",
        "Statesville",
        "Albemarle",
        "Marion",
        "Hickory",
        "Lumberton",
        "Durham",
        "Chapel Hill",
        "Spruce Pine",
        "Burlington",
        "Oxford",
        "Morehead City",
        "Windsor",
        "Elkin",
        "Edenton",
        "Lincolnton",
        "Black Mountain",
        "Linville",
        "Shelby",
        "Goldsboro",
        "Southport",
        "Highlands",
        "Raleigh",
        "Raeford",
        "Sanford",
        "Winston Salem",
        "Gastonia",
        "Monroe",
        "Morganton",
        "Plymouth",
        "Charlotte",
        "Columbus",
        "Jefferson",
        "Wilson",
        "Kinston",
        "Mocksville",
        "Smithfield",
        "Clinton",
        "Matthews",
        "Sparta",
        "Williamston",
        "Henderson",
        "Elizabethtown",
        "Fayetteville",
        "Supply",
        "Roanoke Rapids",
        "Lexington",
        "Huntersville",
        "Franklin",
        "Kenansville",
        "Rutherfordton",
        "Cary",
        "Asheville",
        "Whiteville",
        "Garner",
        "Boone",
        "North Wilkesboro",
        "Concord",
        "Hendersonville",
        "Burgaw",
        "Jacksonville",
        "Troy",
        "Butner",
        "Erwin",
        "Fort Bragg",
        "Greensboro",
        "Wadesboro",
        "Sylva",
        "Ahoskie",
        "Nags Head",
        "Roxboro",
        "Eden",
        "Washington",
        "New Bern",
        "Mooresville",
        "Dunn",
        "Tarboro",
        "Laurinburg",
        "Wilmington",
        "Camp Lejeune",
        "Thomasville",
        "High Point"
    ],
    "NE": [
        "Lincoln",
        "Kearney",
        "Omaha",
        "Grand Island",
        "Hastings",
        "Scottsbluff",
        "North Platte",
        "Fremont",
        "Papillion",
        "Columbus",
        "Norfolk",
        "Bellevue",
        "Alma",
        "Geneva",
        "Pawnee City",
        "Lynch",
        "Hebron",
        "Kimball",
        "Minden",
        "Wahoo",
        "Henderson",
        "Syracuse",
        "Oshkosh",
        "Franklin",
        "Genoa",
        "Gothenburg",
        "Osceola",
        "Superior",
        "Red Cloud",
        "Bridgeport",
        "Fairbury",
        "Aurora",
        "West Point",
        "Schuyler",
        "Auburn",
        "Ainsworth",
        "Neligh",
        "Cozad",
        "Central City",
        "O' Neill",
        "Friend",
        "Creighton",
        "David City",
        "Bassett",
        "Albion",
        "Callaway",
        "York",
        "St Paul",
        "Seward",
        "Benkelman",
        "Chadron",
        "Nebraska City",
        "Atkinson",
        "Valentine",
        "Wayne",
        "Plainview",
        "Osmond",
        "Cambridge",
        "Pender",
        "Tecumseh",
        "Imperial",
        "Falls City",
        "Ord",
        "Crete",
        "Ogallala",
        "Grant",
        "Sidney",
        "Gordon",
        "Blair",
        "Alliance",
        "Lexington",
        "Holdrege",
        "Mccook",
        "Beatrice",
        "Broken Bow",
        "Boys Town"
    ],
    "NV": [
        "Reno",
        "Las Vegas",
        "North Las Vegas",
        "Elko",
        "Henderson",
        "Carson City",
        "Nellis Afb",
        "Sparks",
        "Hawthorne",
        "Incline Village",
        "Ely",
        "Batte Mtn",
        "Lovelock",
        "Gardnerville",
        "Mesquite",
        "Winnemucca",
        "Boulder City",
        "Pahrump",
        "Caliente",
        "Fallon",
        "Yerington"
    ],
    "NH": [
        "Concord",
        "Lebanon",
        "Laconia",
        "Nashua",
        "Manchester",
        "Rochester",
        "Derry",
        "Dover",
        "Keene",
        "Exeter",
        "Portsmouth",
        "Colebrook",
        "Woodsville",
        "Littleton",
        "Lancaster",
        "New London",
        "Franklin",
        "North Conway",
        "Claremont",
        "Peterborough",
        "Berlin",
        "Plymouth",
        "Wolfeboro",
        "Hampstead"
    ],
    "NJ": [
        "Hackensack",
        "Newark",
        "North Bergen",
        "Flemington",
        "Passaic",
        "Teaneck",
        "Belleville",
        "Plainsboro",
        "Cape May Court House",
        "Ridgewood",
        "Camden",
        "Morristown",
        "Jersey City",
        "Pompton Plains",
        "Paterson",
        "Trenton",
        "Voorhees",
        "Rahway",
        "Bayonne",
        "Elizabeth",
        "Newton",
        "Browns Mills",
        "Vineland",
        "Red Bank",
        "New Brunswick",
        "Perth Amboy",
        "Hoboken",
        "Toms River",
        "Pennington",
        "Englewood",
        "Somers Point",
        "Somerville",
        "Denville",
        "Summit",
        "Brick",
        "Montclair",
        "Mount Holly",
        "Paramus",
        "Phillipsburg",
        "Willingboro",
        "Atlantic City",
        "Elmer",
        "Neptune",
        "Long Branch",
        "Livingston",
        "East Orange",
        "Lakewood",
        "Stratford",
        "Salem",
        "Edison",
        "Hamilton",
        "Freehold",
        "Holmdel",
        "Manahawkin",
        "Hackettstown",
        "Secaucus",
        "Westwood",
        "Marlton",
        "Hammonton",
        "Piscataway",
        "Belle Mead",
        "Greystone Park",
        "Blackwood",
        "Wyckoff",
        "Cedar Grove",
        "Westampton",
        "Pemberton",
        "Berkeley Heights"
    ],
    "NM": [
        "Albuquerque",
        "Santa Fe",
        "Las Vegas",
        "Alamogordo",
        "Farmington",
        "Roswell",
        "Espanola",
        "Las Cruces",
        "Clovis",
        "Artesia",
        "Los Alamos",
        "Gallup",
        "Mescalero",
        "Shiprock",
        "Zuni",
        "Crownpoint",
        "Carlsbad",
        "Hobbs",
        "Santa Rosa",
        "San Fidel",
        "Portales",
        "Rio Rancho",
        "T Or C",
        "Socorro",
        "Tucumcari",
        "Clayton",
        "Lovington",
        "Ruidoso",
        "Raton",
        "Grants",
        "Deming",
        "Taos",
        "Silver City",
        "Santa Teresa"
    ],
    "NY": [
        "Buffalo",
        "Yonkers",
        "Warsaw",
        "Bronx",
        "Binghamton",
        "Albany",
        "Jamaica",
        "Brooklyn",
        "Poughkeepsie",
        "New York",
        "East Meadow",
        "Staten Island",
        "Newark",
        "Norwich",
        "Bay Shore",
        "New Hartfd",
        "Huntington",
        "Amsterdam",
        "Rhinebeck",
        "Flushing",
        "Geneva",
        "Niagara Falls",
        "Batavia",
        "Canandaigua",
        "Saranac Lake",
        "Malone",
        "Oneonta",
        "Mount Vernon",
        "Elmira",
        "Hudson",
        "Wellsville",
        "Kenmore",
        "Olean",
        "Nyack",
        "Manhasset",
        "Riverhead",
        "Springville",
        "Oneida",
        "Rochester",
        "Middletown",
        "Elmhurst",
        "Port Jervis",
        "Cooperstown",
        "Syracuse",
        "Patchogue",
        "Bath",
        "Hornell",
        "Schenectady",
        "Watertown",
        "Suffern",
        "Mount Kisco",
        "Lockport",
        "Westfield",
        "Cortland",
        "Troy",
        "Glen Cove",
        "Roslyn",
        "New Rochelle",
        "Port Jefferson",
        "Lewiston",
        "Glens Falls",
        "New Hyde Park",
        "Potsdam",
        "Oceanside",
        "Warwick",
        "Ogdensburg",
        "Rome",
        "Oswego",
        "Saratoga Springs",
        "Massena",
        "Kingston",
        "Dunkirk",
        "Valhalla",
        "Auburn",
        "Dansville",
        "Jamestown",
        "Utica",
        "Plattsburgh",
        "Rockville Centre",
        "West Point",
        "Sleepy Hollow",
        "Newburgh",
        "Clifton Springs",
        "Cortlandt Manor",
        "Carmel",
        "Gloversville",
        "Corning",
        "West Islip",
        "White Plains",
        "Ithaca",
        "Plainview",
        "Bethpage",
        "Harris",
        "Stony Brook",
        "Far Rockaway",
        "Smithtown",
        "West Haverstraw",
        "Cuba",
        "Elizabethtown",
        "Callicoon",
        "Margaretville",
        "Delhi",
        "Star Lake",
        "Alexandria Bay",
        "Ellenville",
        "Little Falls",
        "Walton",
        "Montour Falls",
        "Penn Yan",
        "Gouverneur",
        "Hamilton",
        "Lowville",
        "Carthage",
        "Medina",
        "Cobleskill",
        "Katonah",
        "Queens Village",
        "West Brentwood",
        "Orangeburg",
        "Amityville",
        "New Hampton",
        "Dix Hills",
        "West Seneca"
    ],
    "ND": [
        "Bismarck",
        "Minot",
        "Fargo",
        "Grand Forks",
        "Belcourt",
        "Fort Yates",
        "Tioga",
        "Stanley",
        "Watford City",
        "Garrison",
        "Turtle Lake",
        "Kenmare",
        "Cooperstown",
        "Bottineau",
        "Mcville",
        "Mayville",
        "Hazen",
        "Lisbon",
        "Northwood",
        "Bowman",
        "Elgin",
        "Oakes",
        "Rolla",
        "Carrington",
        "Cavalier",
        "Grafton",
        "Wishek",
        "Ashley",
        "Langdon",
        "Valley City",
        "Crosby",
        "Park River",
        "Harvey",
        "Linton",
        "Hillsboro",
        "Hettinger",
        "Cando",
        "Rugby",
        "Devils Lake",
        "Williston",
        "Jamestown",
        "Dickinson"
    ],
    "OH": [
        "Cincinnati",
        "Ashland",
        "Columbus",
        "Portsmouth",
        "Lima",
        "Dover",
        "Marion",
        "Westerville",
        "Sidney",
        "Athens",
        "Akron",
        "Sandusky",
        "Xenia",
        "Bowling Green",
        "Saint Marys",
        "Wooster",
        "Cleveland",
        "Zanesville",
        "Mount Vernon",
        "Parma",
        "Greenville",
        "Oxford",
        "Toledo",
        "Dayton",
        "Gallipolis",
        "Warren",
        "Fairfield",
        "Coldwater",
        "Youngstown",
        "Norwalk",
        "Wright-Patterson Afb",
        "Canton",
        "Van Wert",
        "Lancaster",
        "Richmond Heights",
        "Franklin",
        "Ravenna",
        "Kettering",
        "Martins Ferry",
        "Oregon",
        "Euclid",
        "Springfield",
        "Tiffin",
        "Maumee",
        "Medina",
        "Marysville",
        "Findlay",
        "East Liverpool",
        "Concord",
        "Bellevue",
        "Coshocton",
        "Mansfield",
        "Bryan",
        "Westlake",
        "Ashtabula",
        "Alliance",
        "Hamilton",
        "Garfield Heights",
        "Warrensville Heights",
        "Elyria",
        "Marietta",
        "Millersburg",
        "Cuyahoga Falls",
        "Middleburg Heights",
        "Fremont",
        "Chillicothe",
        "Circleville",
        "Lorain",
        "Troy",
        "Wilmington",
        "Salem",
        "London",
        "Chardon",
        "Bellefontaine",
        "Cambridge",
        "Delaware",
        "Steubenville",
        "Newark",
        "Mayfield Heights",
        "Batavia",
        "Miamisburg",
        "Rock Creek",
        "New Albany",
        "Defiance",
        "Boardman",
        "Dublin",
        "West Chester",
        "Canal Winchester",
        "Beachwood",
        "Beaver Creek",
        "Avon",
        "Ontario",
        "Paulding",
        "Hicksville",
        "Dennison",
        "Lodi",
        "Greenfield",
        "Oberlin",
        "Geneva",
        "Conneaut",
        "Napoleon",
        "Willard",
        "Cadiz",
        "Urbana",
        "Mount Gilead",
        "Port Clinton",
        "Kenton",
        "Bucyrus",
        "Fostoria",
        "Jackson",
        "Barnesville",
        "Bluffton",
        "Orrville",
        "Shelby",
        "Galion",
        "Seaman",
        "Montpelier",
        "Upper Sandusky",
        "Logan",
        "Washington Ch",
        "Hillsboro",
        "Wauseon",
        "Waverly",
        "Northfield",
        "Willoughby",
        "Massillon",
        "Mason",
        "Middle Point",
        "Hudson",
        "Georgetown"
    ],
    "OK": [
        "Tulsa",
        "Woodward",
        "Miami",
        "Ponca City",
        "Norman",
        "Oklahoma City",
        "Durant",
        "Pryor",
        "Enid",
        "Bartlesville",
        "Elk City",
        "Ada",
        "Altus",
        "Duncan",
        "Muskogee",
        "Clinton",
        "Blackwell",
        "Mcalester",
        "Claremore",
        "Jenks",
        "Ardmore",
        "Stillwater",
        "Chickasha",
        "Lawton",
        "Okmulgee",
        "Antlers",
        "Tahlequah",
        "Midwest City",
        "Cushing",
        "Hugo",
        "Sallisaw",
        "Grove",
        "Perry",
        "Shawnee",
        "Hobart",
        "Purcell",
        "Wagoner",
        "Talihina",
        "Stilwell",
        "Henryetta",
        "Yukon",
        "Lindsay",
        "Edmond",
        "Owasso",
        "Seminole",
        "Broken Arrow",
        "Vinita",
        "Pauls Valley",
        "Atoka",
        "Prague",
        "Watonga",
        "Cheyenne",
        "Tishomingo",
        "Nowata",
        "Marietta",
        "Boise City",
        "Pawhuska",
        "Healdton",
        "Waurika",
        "Sapulpa",
        "Kingfisher",
        "Anadarko",
        "Stroud",
        "Guthrie",
        "Fairfax",
        "Coalgate",
        "Cleveland",
        "Holdenville",
        "Beaver",
        "Weatherford",
        "Buffalo",
        "Cordell",
        "Madill",
        "Okeene",
        "Sulphur",
        "Fairview",
        "Mangum",
        "Drumright",
        "Seiling",
        "Okemah",
        "Carnegie",
        "Stigler",
        "Shattuck",
        "Poteau",
        "Hollis",
        "Guymon",
        "Alva",
        "Idabel",
        "Fort Supply"
    ],
    "OR": [
        "The Dalles",
        "Grants Pass",
        "Portland",
        "Ashland",
        "Corvallis",
        "Medford",
        "Springfield",
        "Hillsboro",
        "Albany",
        "Gresham",
        "Roseburg",
        "Silverton",
        "Eugene",
        "Newberg",
        "Oregon City",
        "Redmond",
        "Bend",
        "Klamath Falls",
        "Salem",
        "Ontario",
        "Stayton",
        "Mcminnville",
        "Milwaukie",
        "Tualatin",
        "Coos Bay",
        "Clackamas",
        "Cottage Grove",
        "Lincoln City",
        "Seaside",
        "Bandon",
        "John Day",
        "Enterprise",
        "Burns",
        "Dallas",
        "Lakeview",
        "Heppner",
        "Reedsport",
        "Coquille",
        "Prineville",
        "Newport",
        "Baker City",
        "Florence",
        "Tillamook",
        "Hood River",
        "Pendleton",
        "Astoria",
        "La Grande",
        "Gold Beach",
        "Lebanon",
        "Madras",
        "Hermiston"
    ],
    "PA": [
        "Scranton",
        "Mc Keesport",
        "Bloomsburg",
        "Camp Hill",
        "Danville",
        "Erie",
        "Lansdale",
        "Lewisburg",
        "New Castle",
        "Philadelphia",
        "Pittsburgh",
        "Pottsville",
        "Natrona",
        "Quakertown",
        "Beaver",
        "Sewickley",
        "Somerset",
        "Uniontown",
        "Washington",
        "West Reading",
        "Williamsport",
        "York",
        "Lewistown",
        "Bethlehem",
        "Clearfield",
        "Huntingdon",
        "Sellersville",
        "Carlisle",
        "Roaring Spring",
        "Gettysburg",
        "Lebanon",
        "Harrisburg",
        "Lititz",
        "Bristol",
        "Lock Haven",
        "Berwick",
        "Altoona",
        "Coatesville",
        "Sayre",
        "Drexel Hill",
        "Dubois",
        "Seneca",
        "Clarion",
        "Reading",
        "Meadowbrook",
        "Lancaster",
        "Kane",
        "Johnstown",
        "Windber",
        "Meadville",
        "Norristown",
        "Everett",
        "Pottstown",
        "Honesdale",
        "Phoenixville",
        "Allentown",
        "Wilkes-Barre",
        "Waynesboro",
        "Bryn Mawr",
        "Greensburg",
        "Warren",
        "Monongahela",
        "Waynesburg",
        "Chambersburg",
        "Paoli",
        "Darby",
        "Mckees Rocks",
        "Canonsburg",
        "Easton",
        "Kittanning",
        "Butler",
        "Indiana",
        "Greenville",
        "West Chester",
        "Upland",
        "Coaldale",
        "Connellsville",
        "Hazleton",
        "Tunkhannock",
        "Wynnewood",
        "Punxsutawney",
        "East Stroudsburg",
        "Doylestown",
        "Sharon",
        "Mount Pleasant",
        "Latrobe",
        "West Grove",
        "Media",
        "Ephrata",
        "Abington",
        "Hanover",
        "Hershey",
        "Langhorne",
        "Jefferson Hills",
        "Grove City",
        "Monroeville",
        "State College",
        "Wilkes Barre",
        "Eagleville",
        "Transfer",
        "Wyomissing",
        "Bensalem",
        "Royersford",
        "East Norriton",
        "Stroudsburg",
        "Orwigsburg",
        "Jersey Shore",
        "Muncy",
        "Meyersdale",
        "Mcconnellsburg",
        "Renovo",
        "Troy",
        "Montrose",
        "Tyrone",
        "Corry",
        "Susquehanna",
        "Brookville",
        "Coudersport",
        "Titusville",
        "Saint Marys",
        "Wellsboro",
        "Hastings",
        "Clarks Summit",
        "Wernersville",
        "North Warren",
        "Mt Gretna",
        "Torrance",
        "Ambler",
        "Kingston",
        "Centre Hall",
        "Fort Washington",
        "Shippensburg"
    ],
    "RI": [
        "Providence",
        "North Providence",
        "Newport",
        "Wakefield",
        "Warwick",
        "Woonsocket",
        "Westerly",
        "East Providence"
    ],
    "SC": [
        "Rock Hill",
        "Charleston",
        "Dillon",
        "Spartanburg",
        "Seneca",
        "Hartsville",
        "Pickens",
        "Easley",
        "Columbia",
        "Chester",
        "Georgetown",
        "Greenville",
        "Anderson",
        "Walterboro",
        "Greer",
        "Lancaster",
        "Simpsonville",
        "Clinton",
        "Gaffney",
        "Camden",
        "Conway",
        "Florence",
        "Newberry",
        "Mullins",
        "Lake City",
        "Beaufort",
        "Orangeburg",
        "Sumter",
        "Greenwood",
        "Varnville",
        "West Columbia",
        "Hilton Head Island",
        "Aiken",
        "Myrtle Beach",
        "Mount Pleasant",
        "Murrells Inlet",
        "Hardeeville",
        "Loris",
        "Cheraw",
        "Union",
        "Manning",
        "Summerville",
        "Fairfax",
        "Abbeville",
        "Kingstree",
        "Edgefield",
        "Travelers Rest"
    ],
    "SD": [
        "Watertown",
        "Brookings",
        "Yankton",
        "Mitchell",
        "Aberdeen",
        "Pierre",
        "Sioux Falls",
        "Spearfish",
        "Rapid City",
        "Eagle Butte",
        "Rosebud",
        "Dakota Dunes",
        "Pine Ridge",
        "Madison",
        "Faulkton",
        "Gettysburg",
        "Armour",
        "Platte",
        "Clear Lake",
        "Eureka",
        "Burke",
        "Flandreau",
        "Webster",
        "Britton",
        "Freeman",
        "Martin",
        "Wagner",
        "Redfield",
        "Scotland",
        "Bowdle",
        "Philip",
        "Deadwood",
        "Sturgis",
        "Hot Springs",
        "Custer",
        "Wessington Springs",
        "Mobridge",
        "Milbank",
        "Tyndall",
        "Viborg",
        "Chamberlain",
        "Parkston",
        "Dell Rapids",
        "De Smet",
        "Canton",
        "Winner",
        "Huron",
        "Vermillion",
        "Miller",
        "Gregory",
        "Sisseton"
    ],
    "TN": [
        "Erwin",
        "Jackson",
        "Gallatin",
        "Nashville",
        "Manchester",
        "Lexington",
        "Crossville",
        "Waynesboro",
        "Maryville",
        "Bristol",
        "Knoxville",
        "Huntingdon",
        "Kingsport",
        "Elizabethton",
        "Pulaski",
        "Franklin",
        "Morristown",
        "Harriman",
        "Rogersville",
        "La Follette",
        "Oak Ridge",
        "Clarksville",
        "Linden",
        "Dickson",
        "Memphis",
        "Greeneville",
        "Murfreesboro",
        "Jefferson City",
        "Tazewell",
        "Winchester",
        "Cookeville",
        "Milan",
        "Martin",
        "Johnson City",
        "Springfield",
        "Athens",
        "Dyersburg",
        "Columbia",
        "Sevierville",
        "Sweetwater",
        "Chattanooga",
        "Fayetteville",
        "Savannah",
        "Lenoir City",
        "Powell",
        "Union City",
        "Covington",
        "Paris",
        "Shelbyville",
        "Tullahoma",
        "Smithville",
        "Hermitage",
        "Mc Minnville",
        "Newport",
        "Lawrenceburg",
        "Cleveland",
        "Livingston",
        "Sparta",
        "Lebanon",
        "Hendersonville",
        "Woodbury",
        "Smyrna",
        "Bartlett",
        "Oneida",
        "Centerville",
        "Hartsville",
        "Waverly",
        "Mountain City",
        "Lafayette",
        "Pikeville",
        "Carthage",
        "Lewisburg",
        "Dayton",
        "Ashland City",
        "Sneedville",
        "Ripley",
        "Camden",
        "Bolivar",
        "Erin",
        "Rocky Top"
    ],
    "TX": [
        "El Paso",
        "Kerrville",
        "Wichita Falls",
        "Bryan",
        "Dallas",
        "Galveston",
        "Victoria",
        "Brownsville",
        "Laredo",
        "Longview",
        "Harlingen",
        "Beaumont",
        "Houston",
        "Fort Worth",
        "Lubbock",
        "Waco",
        "Corpus Christi",
        "Temple",
        "Sweetwater",
        "Austin",
        "San Antonio",
        "Arlington",
        "Lake Jackson",
        "Anson",
        "Irving",
        "Mount Pleasant",
        "Beeville",
        "Tyler",
        "Graham",
        "North Richland Hills",
        "Gainesville",
        "Eagle Pass",
        "Pasadena",
        "Pampa",
        "Seguin",
        "Floresville",
        "Edinburg",
        "Weslaco",
        "Odessa",
        "Midland",
        "Smithville",
        "Andrews",
        "Cleburne",
        "Killeen",
        "Del Rio",
        "Hereford",
        "Kingsville",
        "Jourdanton",
        "Mission",
        "Brenham",
        "Jacksonville",
        "Paris",
        "Texarkana",
        "Weatherford",
        "Amarillo",
        "Carthage",
        "Lufkin",
        "Conroe",
        "Abilene",
        "Gonzales",
        "Sulphur Springs",
        "Jacksboro",
        "Bellville",
        "Decatur",
        "San Marcos",
        "Kaufman",
        "Denison",
        "Richmond",
        "Huntsville",
        "Marlin",
        "Stephenville",
        "Greenville",
        "Childress",
        "Columbus",
        "Waxahachie",
        "Athens",
        "Livingston",
        "Brownfield",
        "Mexia",
        "Mckinney",
        "Eastland",
        "Azle",
        "Baytown",
        "Corsicana",
        "Glen Rose",
        "Woodville",
        "Bay City",
        "Sherman",
        "Henderson",
        "Lamesa",
        "Breckenridge",
        "Nacogdoches",
        "Port Arthur",
        "Richardson",
        "Plainview",
        "Grapevine",
        "Mineral Wells",
        "San Angelo",
        "Jasper",
        "Canadian",
        "Vernon",
        "Seymour",
        "Brownwood",
        "Granbury",
        "Cuero",
        "Fredericksburg",
        "Aransas Pass",
        "Webster",
        "Denton",
        "Bedford",
        "Nocona",
        "Plano",
        "Big Spring",
        "Rio Grande City",
        "Fairfield",
        "Lewisville",
        "Tomball",
        "Burleson",
        "Humble",
        "Mesquite",
        "El Campo",
        "Littlefield",
        "Fort Sam Houston",
        "Nassau Bay",
        "Fort Hood",
        "Mcallen",
        "Round Rock",
        "Carrollton",
        "Rowlett",
        "Palestine",
        "Levelland",
        "Kingwood",
        "Sugar Land",
        "Alice",
        "Ennis",
        "Allen",
        "Katy",
        "Frisco",
        "The Woodlands",
        "Trophy Club",
        "Southlake",
        "Friona",
        "Big Lake",
        "Groesbeck",
        "Eldorado",
        "Caldwell",
        "Junction",
        "Iraan",
        "Denver City",
        "Mccamey",
        "Ballinger",
        "Sweeny",
        "Eagle Lake",
        "Rotan",
        "Kermit",
        "Winters",
        "Madisonville",
        "Refugio",
        "Aspermont",
        "Anahuac",
        "Navasota",
        "Lampasas",
        "Sonora",
        "Eden",
        "Winnie",
        "Rankin",
        "Hondo",
        "Dalhart",
        "Palacios",
        "Stanton",
        "Wheeler",
        "Muenster",
        "Lockney",
        "Van Horn",
        "Throckmorton",
        "Shamrock",
        "Haskell",
        "Colorado City",
        "Electra",
        "Spearman",
        "Crosbyton",
        "Yoakum",
        "Coleman",
        "Brady",
        "Tulia",
        "Dimmitt",
        "Tahoka",
        "Quanah",
        "Crane",
        "Olney",
        "Wellington",
        "Port Lavaca",
        "Seminole",
        "Perryton",
        "San Augustine",
        "Hemphill",
        "Henrietta",
        "Edna",
        "Kenedy",
        "Burnet",
        "Morton",
        "Pittsburg",
        "Borger",
        "Bonham",
        "Luling",
        "Muleshoe",
        "Monahans",
        "Taylor",
        "Liberty",
        "Hallettsville",
        "Pecos",
        "Alpine",
        "Gatesville",
        "Quitman",
        "Winnsboro",
        "Comanche",
        "Snyder",
        "Clifton",
        "Dumas",
        "Uvalde",
        "Fort Stockton",
        "Carrizo Springs",
        "Pearsall",
        "Hamilton",
        "Crockett",
        "Knox City",
        "Hillsboro",
        "Llano",
        "Terrell",
        "Rusk",
        "Desoto",
        "League City",
        "Belton",
        "Cypress",
        "De Soto",
        "Georgetown",
        "Garland",
        "La Grange",
        "Mansfield",
        "Cedar Park",
        "Rockwall",
        "Kyle",
        "Sunnyvale",
        "Aubrey",
        "Flower Mound",
        "Addison",
        "Harker Heights",
        "Mc Kinney",
        "College Station",
        "Lancaster",
        "New Braunfels",
        "Pearland",
        "Marble Falls",
        "Cleveland",
        "Hurst",
        "Horizon City",
        "Pflugerville",
        "Buda",
        "Lumberton",
        "Bastrop",
        "Spring",
        "Midlothian"
    ],
    "UT": [
        "Provo",
        "Salt Lake City",
        "Ogden",
        "Cedar City",
        "Murray",
        "Price",
        "Payson",
        "Tooele",
        "Logan",
        "Brigham City",
        "Roosevelt",
        "St George",
        "American Fork",
        "Richfield",
        "Vernal",
        "Tremonton",
        "Layton",
        "Bountiful",
        "Orem",
        "Sandy",
        "West Jordan",
        "North Logan",
        "Park City",
        "Riverton",
        "Draper",
        "Spanish Fork",
        "Delta",
        "Fillmore",
        "Moab",
        "Mount Pleasant",
        "Nephi",
        "Milford",
        "Gunnison",
        "Heber City",
        "Monticello",
        "Kanab",
        "Blanding",
        "Panguitch",
        "Beaver",
        "Midvale"
    ],
    "VT": [
        "Barre",
        "Burlington",
        "Rutland",
        "Brattleboro",
        "Bennington",
        "Saint Albans",
        "Townshend",
        "Randolph",
        "Windsor",
        "Saint Johnsbury",
        "Newport",
        "Morrisville",
        "Springfield",
        "Middlebury",
        "Berlin"
    ],
    "VA": [
        "Lebanon",
        "Harrisonburg",
        "Winchester",
        "Norfolk",
        "Charlottesville",
        "South Boston",
        "Portsmouth",
        "Fishersville",
        "Culpeper",
        "Fort Belvoir",
        "Hopewell",
        "Lynchburg",
        "Fredericksburg",
        "Warrenton",
        "Roanoke",
        "Richmond",
        "Front Royal",
        "Onancock",
        "Marion",
        "Alexandria",
        "Newport News",
        "Christiansburg",
        "Leesburg",
        "Suffolk",
        "Manassas",
        "Salem",
        "Arlington",
        "Abingdon",
        "Virginia Beach",
        "Hampton",
        "Richlands",
        "Falls Church",
        "Williamsburg",
        "Petersburg",
        "Mechanicsville",
        "Danville",
        "Tappahannock",
        "Bedford",
        "Rocky Mount",
        "Farmville",
        "Franklin",
        "Emporia",
        "South Hill",
        "Fairfax",
        "Reston",
        "Blacksburg",
        "Wytheville",
        "Woodbridge",
        "Big Stone Gap",
        "Galax",
        "Pulaski",
        "Tazewell",
        "Chesapeake",
        "Low Moor",
        "Grundy",
        "Gloucester",
        "Midlothian",
        "Stafford",
        "Haymarket",
        "Dulles",
        "Hot Springs",
        "Pearisburg",
        "Clintwood",
        "Lexington",
        "Woodstock",
        "Luray",
        "Kilmarnock",
        "Pennington Gap",
        "New Kent",
        "Staunton"
    ],
    "WA": [
        "Walla Walla",
        "Mount Vernon",
        "Seattle",
        "Anacortes",
        "Burien",
        "Everett",
        "Auburn",
        "Wenatchee",
        "Centralia",
        "Lakewood",
        "Olympia",
        "Edmonds",
        "Bellingham",
        "Aberdeen",
        "Moses Lake",
        "Yakima",
        "Toppenish",
        "Bremerton",
        "Longview",
        "Spokane",
        "Vancouver",
        "Bellevue",
        "Kennewick",
        "Richland",
        "Tacoma",
        "Arlington",
        "Port Angeles",
        "Puyallup",
        "Monroe",
        "Renton",
        "Kirkland",
        "Federal Way",
        "Oak Harbor",
        "Gig Harbor",
        "Issaquah",
        "Covington",
        "Pomeroy",
        "Dayton",
        "South Bend",
        "Elma",
        "Davenport",
        "Odessa",
        "Grand Coulee",
        "Chewelah",
        "Newport",
        "Ritzville",
        "Prosser",
        "Leavenworth",
        "Ilwaco",
        "White Salmon",
        "Goldendale",
        "Ephrata",
        "Othello",
        "Morton",
        "Quincy",
        "Tonasket",
        "Republic",
        "Port Townsend",
        "Brewster",
        "Forks",
        "Colville",
        "Colfax",
        "Omak",
        "Sedro Woolley",
        "Sunnyside",
        "Pullman",
        "Clarkston",
        "Ellensburg",
        "Chelan",
        "Enumclaw",
        "Shelton",
        "Pasco",
        "Snoqualmie",
        "Coupeville",
        "Friday Harbor",
        "Medical Lake",
        "Tukwila",
        "Marysville",
        "Lacey"
    ],
    "WV": [
        "Morgantown",
        "Ronceverte",
        "Bridgeport",
        "Huntington",
        "Martinsburg",
        "Point Pleasant",
        "Glen Dale",
        "Charleston",
        "Weirton",
        "South Charleston",
        "Elkins",
        "Weston",
        "Princeton",
        "Fairmont",
        "Logan",
        "Wheeling",
        "Parkersburg",
        "Beckley",
        "New Martinsville",
        "Welch",
        "Philippi",
        "Webster Springs",
        "Grantsville",
        "Sistersville",
        "Spencer",
        "Grafton",
        "Gassaway",
        "Berkeley Springs",
        "Hinton",
        "Romney",
        "Kingwood",
        "Madison",
        "Buckeye",
        "Keyser",
        "Petersburg",
        "Oak Hill",
        "Montgomery",
        "Ranson",
        "Ripley",
        "Buckhannon",
        "Summersville",
        "Clarksburg"
    ],
    "WI": [
        "Stevens Point",
        "La Crosse",
        "Waukesha",
        "Appleton",
        "Rice Lake",
        "Eau Claire",
        "Chippewa Falls",
        "Rhinelander",
        "Kenosha",
        "Mequon",
        "Monroe",
        "Wausau",
        "Wisconsin Rapids",
        "Two Rivers",
        "Sheboygan",
        "Marshfield",
        "Hartford",
        "Portage",
        "Neenah",
        "Green Bay",
        "Milwaukee",
        "Baraboo",
        "Burlington",
        "Oconomowoc",
        "West Bend",
        "Janesville",
        "Fort Atkinson",
        "Beaver Dam",
        "Madison",
        "Fond Du Lac",
        "Woodruff",
        "Prairie Du Sac",
        "Racine",
        "Beloit",
        "Elkhorn",
        "Menomonee Falls",
        "Manitowoc",
        "Mauston",
        "Marinette",
        "Watertown",
        "West Allis",
        "Glendale",
        "Altoona",
        "Oshkosh",
        "Weston",
        "Franklin",
        "Summit",
        "Grafton",
        "Minocqua",
        "New Berlin",
        "Eagle River",
        "Osseo",
        "Wild Rose",
        "Hillsboro",
        "Sparta",
        "Durand",
        "Amery",
        "Friendship",
        "Oconto Falls",
        "Stanley",
        "Darlington",
        "Tomahawk",
        "Bloomer",
        "Barron",
        "Whitehall",
        "Chilton",
        "Osceola",
        "Edgerton",
        "Tomah",
        "Ripon",
        "Lancaster",
        "Neillsville",
        "Medford",
        "Park Falls",
        "New London",
        "Waupun",
        "Ladysmith",
        "Superior",
        "Prairie Du Chien",
        "Grantsburg",
        "Spooner",
        "Black River Falls",
        "Waupaca",
        "Hudson",
        "Hayward",
        "Saint Croix Falls",
        "Columbus",
        "Merrill",
        "Menomonie",
        "Richland Center",
        "Shell Lake",
        "Stoughton",
        "Boscobel",
        "New Richmond",
        "Shawano",
        "Baldwin",
        "Viroqua",
        "River Falls",
        "Antigo",
        "Reedsburg",
        "Dodgeville",
        "Cumberland",
        "Platteville",
        "Berlin",
        "Oconto",
        "Lake Geneva",
        "Sturgeon Bay",
        "Ashland",
        "Wauwatosa",
        "Winnebago"
    ],
    "WY": [
        "Gillette",
        "Sheridan",
        "Riverton",
        "Rock Springs",
        "Casper",
        "Cheyenne",
        "Jackson",
        "Laramie",
        "Evanston",
        "Basin",
        "Douglas",
        "Newcastle",
        "Thermopolis",
        "Wheatland",
        "Worland",
        "Torrington",
        "Buffalo",
        "Lovell",
        "Powell",
        "Sundance",
        "Cody",
        "Afton",
        "Lusk",
        "Kemmerer",
        "Rawlins"
    ]
}
years_experience = [
    "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
    "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
    "21", "22", "23", "24", "25", "More than 25 years"
    ]

unit_specialties = [
    "Burn",
    "Cardiac",
    "Cardiothoracic",
    "Cardiovascular",
    "Case Management",
    "Dermatology",
    "Diabetes",
    "Educator",
    "Endocrine",
    "Gastroenterology",
    "Hematology",
    "Infusion",
    "Labor & Delivery",
    "Medicine",
    "Neonatal",
    "Nephrology",
    "Neurology",
    "Neuroscience",
    "Obstetrics",
    "Occupational Health",
    "Oncology",
    "Orthopedic",
    "Pain",
    "Perinatal",
    "Perioperative",
    "Psychiatric",
    "Pulmonary",
    "Rheumatology",
    "Substance Abuse",
    "Surgical",
    "Toxicology",
    "Trauma",
    "Urology",
    "Wound, Ostomy, and Continence"
]