
years_experience = [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "More than 25 years",
]

leaving_reason = [
    "Transitioning to another unit",
    "Transitioning to a different hospital",
    "Leaving bedside for different nursing role",
    "Pursuing higher education",
    "Leaving nursing completely",
]

unit_specialties = [
    "",
    "Allergy",
    "Burn",
    "Cardiac",
    "Cardiothoracic",
    "Cardiovascular",
    "Dermatology",
    "Diabetes",
    "Education",
    "Emergency",
    "Endocrine",
    "Gastroenterology",
    "Hematology",
    "Infusion",
    "Labor & Delivery",
    "Medicine",
    "Neonatal",
    "Nephrology",
    "Neurology",
    "Neuroscience",
    "Obstetrics",
    "Occupational Health",
    "Oncology",
    "Orthopedic",
    "Pain",
    "Perinatal",
    "Perioperative",
    "Psychiatric",
    "Pulmonary",
    "Research",
    "Rheumatology",
    "Substance Abuse",
    "Surgical",
    "Toxicology",
    "Transplant",
    "Trauma",
    "Urology",
    "Wound, Ostomy, and Continence",
]
